#!/usr/bin/env python

import rospy
from std_msgs.msg import Float64
from sensor_msgs.msg import JointState

def callback(data):
    #rospy.loginfo(data.position[2, 3, 7, 8, 9, 10, 11, 12, 13])
    rospy.loginfo(data.position[0])
        

def statereader():
    rospy.init_node('state_reader', anonymous=True)
    #rospy.Subscriber("joint_states", JointState, callback)
    rospy.wait_for_message("joint_states", callback)
    rospy.spin()


if __name__ == "__main__":
    input_var = input('Enter 1 when you wish to record a position')
    if input_var == 1:
        statereader()

